skinparam arrowThickness             1
skinparam sequence{
    LifeLineBorderColor        #4F4FF4
    ParticipantBorderColor     #0A0A1F
    boxBorderColor             #E0E0F5
    
    boxBackgroundColor         #ECECFE
    
    ArrowColor                 #4F4FF4

    LifeLInebackgroundColor    #D8D8FD

    ParticipantBackgroundColor #D8D8FD

    GroupBorderThickness       1
    GroupBorderColor           #B2B2E6

}

skinparam Actor{
    BorderColor 0A0A1F
    BackgroundColor D8D8FD
    BorderThickness 1
}

skinparam Note{
    FontColor 0A0A1F
    backgroundColor white
    BorderColor 0A0A1F
}


skinparam Database{
    BorderColor        #4F4FF4
    BackgroundColor    #ECECFE
    BorderThickness    1
}
skinparam ParticipantPadding         5
skinparam ParticipantBorderThickness 1
skinparam Shadowing                  false
skinparam BoxPadding                 10
skinparam roundcorner                6
skinparam backgroundColor            white 
